# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/noobie/007.jpg'

# Special
background='#0A092C'
foreground='#8cc9df'
cursor='#8cc9df'

# Colors
color0='#0A092C'
color1='#E5AF6B'
color2='#284A97'
color3='#286196'
color4='#556199'
color5='#A67CAC'
color6='#2B8DB2'
color7='#8cc9df'
color8='#628c9c'
color9='#E5AF6B'
color10='#284A97'
color11='#286196'
color12='#556199'
color13='#A67CAC'
color14='#2B8DB2'
color15='#8cc9df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
